version: '3.8'
services:
  server-1:
    build: .
    container_name: server-1
    ports:
      - "8081:8080"
    environment:
      - SERVER_PORT=8080
      - SERVER_NAME=server-1

  server-2:
    build: .
    container_name: server-2
    ports:
      - "8082:8080"
    environment:
      - SERVER_PORT=8080
      - SERVER_NAME=server-2
