version: '3.8'

services:
  server:
    build: .
    ports:
      - "7777:7777/tcp"
      - "7778:7778/udp"
    networks:
      - dueling-network

  client:
    build: .
    command: >
      sh -c '
        echo "Aguardando o servidor..."
        sleep 5
        echo "Iniciando cliente em modo: ${BOT_MODE} com cenário: ${BOT_SCENARIO}"
        java -cp app.jar GameClient ${BOT_MODE} ${BOT_SCENARIO}
      '
    depends_on:
      - server
    environment:
      - SERVER_HOST=server
      - BOT_MODE=${BOT_MODE:-autobot}
      - BOT_SCENARIO=${BOT_SCENARIO}
    networks:
      - dueling-network

networks:
  dueling-network:
    driver: bridge