server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      httpclient:
        connect-timeout: 5000
        response-timeout: 10s
      loadbalancer:
        enabled: false  # Desativar load balancer para usar URLs diretas
        cache:
          enabled: true
      routes:
        # Route for authentication requests (no JWT filter)
        - id: auth-route
          uri: http://server-1:8080
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api/(?<segment>.*), /api/${segment}
        
        # Route for API requests to game microservices
        - id: game-create-match
          uri: http://server-1:8080
          predicates:
            - Path=/api/match/**
          filters:
            - JwtAuthenticationFilter  # Custom filter for JWT validation
            - RewritePath=/api/(?<segment>.*), /api/${segment}
        
        - id: game-move
          uri: http://server-1:8080
          predicates:
            - Path=/api/move/**
          filters:
            - JwtAuthenticationFilter
            - RewritePath=/api/(?<segment>.*), /api/${segment}
        
        - id: game-state
          uri: http://server-1:8080
          predicates:
            - Path=/api/state/**
          filters:
            - JwtAuthenticationFilter
            - RewritePath=/api/(?<segment>.*), /api/${segment}
        
        - id: game-user
          uri: http://server-1:8080
          predicates:
            - Path=/api/user/**
          filters:
            - JwtAuthenticationFilter
            - RewritePath=/api/(?<segment>.*), /api/${segment}
        
        # Route for WebSocket connections
        - id: websocket-route
          uri: ws://server-1:8080
          predicates:
            - Path=/ws/**
          filters:
            - JwtAuthenticationFilter  # Custom filter for JWT validation
            - RewritePath=/ws/(?<segment>.*), /ws/${segment}
       
      # Global filters configuration
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:mySecretKeyForDuelingProtocolThatShouldBeLongerThan256Bits}  # Default secret, should be overridden in production
  expiration: 86400000  # 24 hours in milliseconds

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive: DEBUG