#!/bin/bash
# Script de configuração para ambiente distribuído do Protocolo de Duelo
echo "=== Configuração de Ambiente Distribuído ==="
echo ""
echo "Este script ajuda a configurar o Protocolo de Duelo em máquinas diferentes."
echo ""
echo "Componentes do sistema:"
echo "1. Banco de Dados (PostgreSQL) - Apenas 1 instância"
echo "2. Cache (Redis Sentinel) - Cluster Redis"
echo "3. Servidor de Jogo - Lógica do jogo"
echo "4. Gateway API - Proxy reverso"
echo "5. Clientes - Jogo propriamente dito"
echo ""
echo "Requisitos:"
echo "- Todos os computadores devem estar na mesma rede ou ter IP público acessível"
echo "- As portas 8080 (gateway), 8083 (servidor), 5432 (PostgreSQL), 6379 (Redis) e sentinelas Redis devem estar abertas"
echo "- Java 21+ instalado em todas as máquinas que rodarão Java"
echo "- Maven instalado para compilação (opcional se usar JARs pré-compilados)"
echo ""
echo "Recomendação de arquitetura:"
echo "Opção 1: PostgreSQL e Redis em máquina dedicada, gateway e servidor em outra, clientes em suas próprias máquinas"
echo "Opção 2: PostgreSQL, Redis e Servidor em servidor central, Gateway em máquina intermediária, Clientes distribuídos"
echo ""
echo "Para preparar os JARs em cada máquina:"
echo "  cd /caminho/do/projeto"
echo "  mvn clean package -DskipTests"
echo ""
echo "Os JARs estarão disponíveis em:"
echo "  dueling-gateway/target/dueling-gateway-1.0-SNAPSHOT.jar"
echo "  dueling-server/target/dueling-server-1.0-SNAPSHOT.jar" 
echo "  dueling-client/target/dueling-client-1.0-SNAPSHOT.jar"
echo ""
echo "Scripts para ambiente distribuído:"
echo "  start_server_remote.sh  - Para iniciar o servidor em máquina remota"
echo "  start_gateway_remote.sh - Para iniciar o gateway em máquina remota" 
echo "  start_client_remote.sh  - Para iniciar o cliente em máquina remota"
echo ""
echo "Para ambiente local (mesma máquina):"
echo "  start_game.sh           - Inicia todos os serviços localmente"
echo ""
echo "Lembre-se de:"
echo "- Configurar corretamente os IPs nas variáveis de ambiente"
echo "- Verificar se firewalls permitem conexões nas portas necessárias"
echo "- Garantir que o PostgreSQL e Redis estejam acessíveis pelas outras máquinas"