sequenceDiagram
    actor P1 as Jogador 1
    actor P2 as Jogador 2
    participant CH1 as ClientHandler 1
    participant CH2 as ClientHandler 2
    participant GF as GameFacade
    participant MS as ConcurrentMatchmakingService
    participant GS as GameSession

    P1->>CH1: Envia Comando "MATCHMAKING"
    activate CH1
    CH1->>GF: enterMatchmaking(player1)
    activate GF
    GF->>MS: addPlayerToQueue(player1)
    activate MS
    MS-->>GF: (Fila ainda não tem 2 jogadores)
    deactivate MS
    GF-->>CH1: 
    deactivate GF
    CH1-->>P1: Resposta "SUCCESS:Você entrou na fila."
    deactivate CH1

    P2->>CH2: Envia Comando "MATCHMAKING"
    activate CH2
    CH2->>GF: enterMatchmaking(player2)
    activate GF
    GF->>MS: addPlayerToQueue(player2)
    activate MS
    MS->>MS: findMatch()
    MS-->>GF: Optional.of(Match(p1, p2))
    deactivate MS
    
    GF->>GF: tryToCreateMatch()
    GF->>GS: new GameSession(p1, p2)
    activate GS
    GS->>GS: startGame()
    GS-->>GF: 
    deactivate GS
    
    GF-->>CH1: Notifica "UPDATE:GAME_START"
    deactivate GF
    activate CH1
    CH1-->>P1: "UPDATE:GAME_START:matchId:p2_nickname"
    deactivate CH1

    GF-->>CH2: Notifica "UPDATE:GAME_START"
    activate CH2
    CH2-->>P2: "UPDATE:GAME_START:matchId:p1_nickname"
    deactivate CH2
